# Generated by Django 4.2.5 on 2023-11-07 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('designing', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='items',
            name='image',
        ),
    ]
