# Generated by Django 4.2.5 on 2023-11-08 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designing', '0003_items_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='image',
            field=models.ImageField(default='', upload_to='image/'),
        ),
    ]
