# Generated by Django 4.2.5 on 2023-11-09 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('designing', '0006_rename_user_blog_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='user',
        ),
    ]
